export const SIGNIN = 'SIGNIN'; 
export const AUTHENTICATED = 'AUTHENTICATED';
export const SIGNOUT = 'SIGNOUT';
export const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS'
export const SIGNUP = 'SIGNUP';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SHOW_AUTH_MESSAGE = 'SHOW_AUTH_MESSAGE'
export const HIDE_AUTH_MESSAGE = 'HIDE_AUTH_MESSAGE'
export const SHOW_LOADING = 'SHOW_LOADING'
export const AUTH_TOKEN = 'auth_token'

export const CREATE_USER = 'CREATE_USER'; 
export const GET_USERS = 'GET_USERS'; 
export const GET_USER = 'GET_USER'; 
export const UPDATE_USER = 'UPDATE_USER'; 
export const DELETE_USER = 'DELETE_USER'; 

export const GET_ME = 'GET_ME'; 
export const UPDATE_ME = 'UPDATE_ME'; 
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD'; 
export const DELETE_ME = 'DELETE_ME';

export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const GET_PRODUCTS = 'GET_PRODUCTS'; 
export const GET_PRODUCT = 'GET_PRODUCT'; 
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT'; 
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const GET_MY_PRODUCTS = 'GET_MY_PRODUCTS';

export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const GET_CATEGORIES = 'GET_CATEGORIES'; 
export const GET_CATEGORY = 'GET_CATEGORY'; 
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY'; 
export const DELETE_CATEGORY = 'DELETE_CATEGORY';

export const ADD_TO_CART = 'ADD_TO_CART';
export const GET_CART = 'GET_CART';
export const UPDATE_CART = 'UPDATE_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const CLEAR_CART = 'CLEAR_CART';

export const CHECKOUT = 'CHECKOUT';
export const CREATE_BOOKING = 'CREATE_BOOKING';
export const GET_BOOKINGS = 'GET_BOOKINGS'; 
export const GET_BOOKING = 'GET_BOOKING'; 
export const UPDATE_BOOKING = 'UPDATE_BOOKING'; 
export const DELETE_BOOKING = 'DELETE_BOOKING'; 
export const CLEAR_BOOKING = 'CLEAR_BOOKING'; 

export const CREATE_BOOKINGITEM = 'CREATE_BOOKINGITEM';
export const GET_BOOKINGITEMS = 'GET_BOOKINGITEMS'; 
export const GET_BOOKINGITEM = 'GET_BOOKINGITEM'; 
export const UPDATE_BOOKINGITEM = 'UPDATE_BOOKINGITEM'; 
export const DELETE_BOOKINGITEM = 'DELETE_BOOKINGITEM'; 

export const CREATE_WITHDRAWAL = 'CREATE_WITHDRAWAL';
export const GET_WITHDRAWALS = 'GET_WITHDRAWALS'; 
export const GET_WITHDRAWAL = 'GET_WITHDRAWAL'; 
export const UPDATE_WITHDRAWAL = 'UPDATE_WITHDRAWAL'; 
export const DELETE_WITHDRAWAL = 'DELETE_WITHDRAWAL'; 

export const GET_CHATS = 'GET_CHATS';
export const CREATE_CHAT = 'CREATE_CHAT';
export const GET_CHAT = 'GET_CHAT';
export const UPDATE_CHAT = 'UPDATE_CHAT';
export const DELETE_CHAT = 'DELETE_CHAT';

export const CREATE_CLAIM = 'CREATE_CLAIM';
export const GET_CLAIMS = 'GET_CLAIMS';
export const GET_CLAIM = 'GET_CLAIM';
export const UPDATE_CLAIM = 'UPDATE_CLAIM';
export const DELETE_CLAIM = 'DELETE_CLAIM';

export const CREATE_REFUND = 'CREATE_REFUND';
export const GET_REFUNDS = 'GET_REFUNDS';
export const GET_REFUND = 'GET_REFUND';
export const UPDATE_REFUND = 'UPDATE_REFUND';
export const DELETE_REFUND = 'DELETE_REFUND';

export const MESSAGE_COUNT = 'MESSAGE_COUNT';